### ISSUE TITLE
[Help] Trying to import "testspace_colab" using a Jupyter Notebook

### ISSUE THREAD

**Issue by munderseth** [lbrack/testspace-colab#14]
* testspace-colab version: `version 0.1.dev23+g01a1dbc client 2.5.4061`
* Python version: `Python 3.7.3`
* Operating System: `Windows 10`

### Description
Attempting to replicate the *simple_example.ipynb* as described here - https://github.com/lbrack/testspace-colab/blob/main/notebooks/simple_example.ipynb

Using Windows 10.  The `import` is failing. Note that I am using the CLI successfully. 

### What I Did
```
import testspace_colab
```

Following error:

![image](https://user-images.githubusercontent.com/1229367/108531970-28c63b80-728c-11eb-9f62-7bdd49c18553.png)

**Comment by lbrack** [comment]
Did you start the jupyter notebook from ts-colab ?

**Comment by lbrack** [comment]
This is most likely an environment issue setting with VSCode. For some reason, Jupyter Kernels are started outside of the venv which explains the import error. I will try to reproduce/configure VSCode over the weekend

**Comment by lbrack** [comment]
This is really tricky as Jupyter doesn't see the virtual env. 

**From within your virtualenv**, do:

``` console
pip install ipykernel
python3 -m ipykernel install --user --name=testspace-colab # (name can be anything. In this case testspace-colab)
```
This will create kernel configuration for that env
In VSCode, type **Ctrl-Shift-P** and type ```Jupyter: Select a Kernel ```
Select the kernel based on the name above (as show below)

![image](https://user-images.githubusercontent.com/14916861/108556803-7357b000-72ac-11eb-93ac-c8e863c3aa35.png)

![image](https://user-images.githubusercontent.com/14916861/108556158-730ae500-72ab-11eb-8fd3-89f4daa320cd.png)

Here you go

![image](https://user-images.githubusercontent.com/14916861/108557015-c0d41d00-72ac-11eb-8302-52c698b7bd0d.png)

**Comment by munderseth** [comment]
@lbrack still not working for me. Probably operator error (i.e. me).  

- Tried the following: `python3 -m ipykernel install --user --name=my.testspace-colab`
  get

![image](https://user-images.githubusercontent.com/1229367/108566447-4959ba00-72bb-11eb-87b4-3d11da630cf6.png)

I always use `python` with **no** `3`.

I tried it without the `3`:

![image](https://user-images.githubusercontent.com/1229367/108566571-802fd000-72bb-11eb-811e-2601c3f41b23.png)

But I never see `Jupyter: Select a Kernel`

![image](https://user-images.githubusercontent.com/1229367/108566744-c2f1a800-72bb-11eb-9a47-0fd515077539.png)
